---
title: "Creating SQLite database from csv file of primers"
output: html_notebook
---

```{r setup}
library(RSQLite)
library(tidyverse)
library(dbplyr)
source("/home/peegee/primeR/helper.R")
```


Proper columns in future:
- id (primary key?, autoincrement)
- primer_name
- sequence
- concentration
- name #who ordered
- date
- comments
- empty #TRUE/FALSE


```{r clean}

system("rm /home/peegee/primeR/primers.sqlite")
system("rm /home/peegee/primeR/primers.fasta*")

```

```{r open_csv}
all_primers <- read_csv("/home/peegee/primeR/primers.csv", col_names = c("id", 
                                                     "primer_name", 
                                                     "sequence", 
                                                     "concentration"), 
                        skip = 1, trim_ws = TRUE, na = "NA") %>%
  mutate(concentration = ifelse(is.na(concentration), yes = 0, no = concentration),
         name = "Nobody",
         date = lubridate::today(),
         comments = " ",
         empty = FALSE) %>%
  select(id,
         primer_name,
         sequence,
         concentration,
         comments,
         date,
         name,
         empty
         )

all_primers <-
  all_primers %>% 
  anti_join(all_primers[duplicated(all_primers$id),] )

br_primers <- read_csv("/home/peegee/primeR/br_primers.csv") %>%
  mutate(empty = if_else(empty, TRUE, FALSE, FALSE),
         name = "originals") %>%
  select(id,
         primer_name,
         sequence,
         concentration,
         comments,
         date,
         name,
         empty
         )
```

```{r connect}
con <- dbConnect(SQLite(), "/home/peegee/primeR/primers.sqlite")
```

```{r overwrite}
#Delete table
#dbRemoveTable(con, "primers")


dbGetQuery(con, "CREATE TABLE primers
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primer_name TEXT,
  sequence TEXT,
  concentration REAL,
  comments TEXT,
  date TEXT,
  name TEXT,
  empty INTEGER
)")

dbGetQuery(con, "CREATE TABLE br_primers
(
  id TEXT PRIMARY KEY,
  primer_name TEXT,
  sequence TEXT,
  concentration REAL,
  comments TEXT,
  date TEXT,
  name TEXT,
  empty INTEGER
)")

# dbWriteTable(con, 
#              name="primers", 
#              value = all_primers, 
#              overwrite = TRUE)

dbWriteTable(con, "primers", all_primers, append = TRUE)

dbWriteTable(con, "br_primers", br_primers, append = TRUE)
```

```{r check}
dbGetQuery(con, "SELECT * FROM primers LIMIT 5;")
```

```{r initiate_fasta}
for (i in seq_len(con %>% tbl("primers") %>% as_data_frame() %>% nrow()) ){
  con %>% 
    tbl("primers") %>% 
    as_data_frame() %>% 
    .[i,] %>% 
    select(id, sequence) -> new_line
  write_lines(x =paste(">", new_line$id, "\n", new_line$sequence, sep = ""),
              path = "/home/peegee/primeR/primers.fasta", 
              append = TRUE)
}

create_blast_db("/home/peegee/primeR/primers.fasta")

```


```{r disconnect}
dbDisconnect(con)
```